spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/highLearn
    username: root
    password: kaesarsk-7

#  nacos 的配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mix

#  redis 的配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6739
    timeout: 1000

  # rabbitMQ的配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /